apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{values.repoName}}
  namespace: ${{values.namespace}}
  labels:
    app: ${{values.repoName}}
    backstage.io/kubernetes-id: ${{values.repoName}}
    backstage.io/kubernetes-namespace: ${{values.namespace}}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ${{values.repoName}}
  template:
    metadata:
      labels:
        app: ${{values.repoName}}
        backstage.io/kubernetes-id: ${{values.repoName}}
        backstage.io/kubernetes-namespace: ${{values.namespace}}
    spec:
      imagePullSecrets:
        - name: kantia-registry
      containers:
      - name: ${{values.repoName}}
        image: cerebroprd.azurecr.io/${{values.repoName}}:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "30m"
            memory: "100Mi"
          limits:
            cpu: "100m"
            memory: "200Mi"
