parameters:
- name: armConnection
  type: string
- name: env
  type: string

steps:

- task: Kubernetes@1
  displayName: 'kubectl apply env kustomization'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: "_${{ parameters.armConnection }}_"
    azureResourceGroup: '$(ResourceGroupName)'
    kubernetesCluster: '$(AksClusterName)'
    namespace: back
    command: apply
    arguments: -k $(Pipeline.Workspace)/app/overlays/_{{ parameters.env }}_
    checkLatest: true
