parameters:
- name: armConnection
  type: string
- name: env
  type: string

steps:

- task: KubeloginInstaller@0
  inputs:
    kubeloginVersion: 'latest'
    
- task: Kubernetes@1
  displayName: 'kubectl apply env kustomization'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: "${{ '${{ parameters.armConnection }}' }}"
    # azureResourceGroup: '$(ResourceGroupName)'
    azureResourceGroup: 'eb-security-dev-rg'
    kubernetesCluster: 'aks-test-security'
    # kubernetesCluster: '$(AksClusterName)'
    command: apply
    arguments: -k $(Pipeline.Workspace)/app/overlays/${{ '${{ parameters.env}}' }}
    checkLatest: true
